### ISSUE TITLE
The Component is not available on Modern Page

### ISSUE THREAD

**Issue by Debanjan-Roy** [pnp/sp-site-designs-studio#13]
Hi,

I am not able to add the component on the Modern Site Page. The webpart is not appearing in the list , when I am trying to add to it on the Modern page.
I am getting the webpart only  in the classic page.

Is the component only compatible with the Classic page. Can you kindly advise.

**Comment by ypcode** [comment]
Hello, 

It has been designed not to be added by users on pages but rather installed on its own modern site. If you take a look and follow the setup guide mentioned in the readme. Everything should be ready to use without any configuration.

Good that you mention it's available in classic UI... it should not. I indeed never intended to make it work in classic UI...

I hope it will work better for you by running the setup script. Let me know how it goes :)

Best regards
Yannick

**Comment by ypcode** [comment]
Hello @Debanjan-Roy 

Any news regarding your issue ? Does it work better with a proper setup ?

Best regards,
Yannick

**Comment by ypcode** [comment]
Closing this one due to lack of response. Feel free to reopen if relevant :)
