### ISSUE TITLE
Add site logo (or other node)

### ISSUE THREAD

**Issue by PooLP** [pnp/sp-site-designs-studio#17]
Hi,
in JSON schema, we can add a site logo with this node :

{
  "verb": "setSiteLogo",
  "url": "/Customer Event Collateral/logo.jpg"
}

If i add this on JSON panel, this disappear after save.

would it be possible to add this node or the possibility to add nodes which are not yet managed by your webpart in JSON panel?

Thanks

**Comment by ypcode** [comment]
Hello @PooLP,

This site action is supported in the WebPart. However it is possible a validation issue on your input is preventing it to work correctly. Did you try with an absolute URL?

I try to keep in sync with updated site actions. However it's still possible that I miss some updates. I'll leave this issue open until I manage to get some time for it and have a closer look hopefully ASAP. I unfortunately can't promise any date.

If any volunteers on fixing this. I remind that we accept PRs from community. :)

Best regards,
Yannick

**Comment by PooLP** [comment]
It work, my URL was wrong... sorry. i'm close the issue.
