### ISSUE TITLE
'Add Principal to Group' action not working

### ISSUE THREAD

**Issue by Ochechule** [pnp/sp-site-designs-studio#3]
Hi, script action 'Add Principal to Group' is using verb "addPrincipalToGroup". According to [MS doc](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-json-schema#add-users-principals-to-sharepoint-groups) it should be using verb "addPrincipalToSPGroup" (with "SP"). 

Also this action/script is never saved. Even when I try to replace the verb manually in JSON editor.

I'm using app version 2.0.0.10.

**Comment by ypcode** [comment]
Hello @Ochechule ,

Good catch ! I’ll fix it ASAP, hopefully today!
Thank you for using the solution and reporting the issue!

Best regards
Yannick

**Comment by ypcode** [comment]
Hi @Ochechule ,

This should now be fixed. You can get the latest [.sppkg file here](https://github.com/pnp/sp-site-designs-studio/blob/master/setup/package/site-designs-studio-v2.sppkg).
You can simply drop it in your app catalog and override the existing one.

( you can also follow the regular setup procedure, but in this case, it's not absolutely needed )

Hope I helped :)

Regards,
Yannick

**Comment by Ochechule** [comment]
Hi Yannick,
thank you very much for such a quick fix. I will install updated version tomorrow.

Kind regards,
Pavel (Ochechule)
