### ISSUE TITLE
Error Apply-PnPProvisioningTemplate : The specified user c:0-.f|rolemanager|spo-grid-all-users/ could not be found

### ISSUE THREAD

**Issue by SnappyFPV** [pnp/sp-site-designs-studio#6]
Install Script not working in our Tenant:
Error Apply-PnPProvisioningTemplate : The specified user c:0-.f|rolemanager|spo-grid-all-users/ could not be found

**Comment by ypcode** [comment]
Hello,

Good catch ! I will have a look ASAP.
Is it so that external sharing is disabled globally on your tenant ?

Regards,
Yannick

**Comment by SnappyFPV** [comment]
Yes, its off by default. Test it to enable on the site. but didnt solve the issue .

Mit freundlichen Grüßen,
Patrick Eisel

________________________________

**Comment by ypcode** [comment]
Hello Patrick,

According to the error message you mention, it looks like your tenant Id is not appended to it.
Could you please try the command "Get-PnPTenantId" and see if it returns something?
I don't see why that wouldn't work, but it's the only reason I can see now why it wouldn't be appended in the provisioning template.

To unblock you, you may probably try replace the $tenantId variable by your actual tenant Id in the following line of the setup.ps1 file
https://github.com/pnp/sp-site-designs-studio/blob/237d28792ff009e48b57794e9bec8a544406de31/setup/PnPPowershell/setup.ps1#L24
You can get to know your tenant Id following [that doc](https://docs.microsoft.com/en-us/onedrive/find-your-office-365-tenant-id)


Let me know if that helps ?

BTW, do you use the -useMFA argument of the setup script ?

Regards,
Yannick

**Comment by ypcode** [comment]
Hello Patrick,

According to the error message you mention, it looks like your tenant Id is not appended to it.
Could you please try the command "Get-PnPTenantId" and see if it returns something?

**Comment by SnappyFPV** [comment]
Problem was the MFA ... used a generated APP Password for the Admin Account to connect-pnponline - it works without any issues.

**Comment by ypcode** [comment]
Awesome I will make sure to make it works. At worst suggesting a workaround :)

**Comment by ypcode** [comment]
Closing this one since MFA is no longer supported in setup script.
